apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.env.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]
